name = "LPIP"
uuid = "0ecde40a-bebd-11e9-0244-1b8cbc9db53c"
authors = ["Guilherme Bodin <guilherme.b.moraes@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
